name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.dockerhub_AccessToken }}" | docker login -u "rioachyar04" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.dockerhub_username }}/uas-pcc-rio-achyar-2025:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.dockerhub_username }}/uas-pcc-rio-achyar-2025:latest
